leoluz/nvim-dap-go

README.md
lua/dap-go.lua

Implements feature requested in https://github.com/leoluz/nvim-dap-go/issues/17
I also made debug_test return true/false so one can have one keymapping to do something like:
```
function()
if require("dap-go").debug_test() ~= true then
require("dap-go").debug_last_test()
end
end,
```
Plus changed the prints to vim.notify() instead.

add function to re-run the last run debug_test

---

lua/dap-go.lua

Hi, 
Thank you for the work you did on this plugin, it's very valuable to me.
One use case I needed was passing flags when running `Debug Packae` and because I mostly use this setting also having it as a config I can choose from in the list.
This PR allows the user to supply their own configs when setup is called and append them to the existing list of configs.
Example usage 
```lua
require('dap-go').setup({
{
type = "go",
name = "Debug Package + Config",
request = "launch",
program = "${fileDirname}",
args = { "-l", "_infra/kustomize/overlays/config/common" },
}
})
```
And here's what the list of options to choose from would look like in this case.
I'm sorry my formatter took some liberties.  If you would like me to undo those I can.

Allow user supplied configs.

---

lua/dap-go.lua

This PR fixes in the deprecation warnings due to the usage of `treesitter.parse_query` function, which will be removed in the next version of neovim (0.10).

fix deprecation warnings for treesitter parse_query

---

README.md
doc/nvim-dap-go.txt
lua/dap-go.lua

For example, I need to pass `--check-go-version=false` when using unreleased go version.

Add delve option to pass additional args

---

README.md
doc/nvim-dap-go.txt
lua/dap-go.lua

@leoluz, thank you so much for creating such a great DAP for Go. I use it every day at work.
I found that my installation was using a version of `dlv` I could not track down. I deleted every version from my `PATH` environment variable. It was stuck on a version `1.9` or so. It would be interesting to take you through what was going on there if you have any thoughts on what it could be.
Suffice it to say, I was unable to get the debugger working when I upgraded to Go 1.20 and needed to patch in my own path to the `dlv` executable. I figured I would submit the change I made upstream so that if others run into a similar problem, they can set the path to their `dlv` executable manually. This doesn't change the default behavior at all, just allows users to override the exectuable.

Allow configuration of dlv path

---

README.md
lua/dap-go.lua

This should solve #35 and #36.
It is a bit more invasive than I would have liked for a first PR here, but the configuration needs to be accessible for the debug_test local function. If you don't like having the config as an attribute to the module object, I can rewrite this to expose additional `debug_test_with_buildflags(buildflags)` functions instead, but I actually think it is cleaner this way.
Thanks for the plugin, btw :)

allow debugging of files with build tags

---

lua/dap-go.lua

Thanks for the plugin! I used it successfully to attach to a process, however the process selection is tedious and time consuming scanning through the list of processes. Added a filter prompt to use the optional argument in `dap.utils.pick-process`.

attached debugging: filter process list

---

lua/dap-go-ts.lua
lua/dap-go.lua

This PR allows debugging a single nested test.
It also refactor the code separating all treesitter logic in a dedicated file.
fix: https://github.com/leoluz/nvim-dap-go/issues/39

feat: allow debugging a single nested test at any level

---

lua/dap-go.lua

This PR updates `get_arguments` function to use the coroutine which nvim-dap passes.
This fixes the problem that prevents the debugging with arguments not running on some situations.
See https://github.com/mfussenegger/nvim-dap/blob/master/doc/dap.txt#L247-L256

Update get_arguments to handle coroutine correctly

---

lua/dap-go.lua

I assume the treesitter API changed (again) and caused this to start breaking. If I try to run `debug_test()` outside of a test file, then I get an exception for trying to concatenate a nil value. This commit just fixes the "no test found" short-circuit clause to handle empty string or nil.

Handle nil test.name

---

README.md
doc/nvim-dap-go.txt
lua/dap-go.lua

- fixes: https://github.com/leoluz/nvim-dap-go/issues/66
Added the `detached` option so that the windows users can set it to `false` in order to solve the dlv error.

Added detached option to fix windows error

---

lua/dap-go-ts.lua

The `:lua require('dap-go').debug_test()` function is not working for all sub tests. That is because right now, the TreeSitter [subtests_query](https://github.com/leoluz/nvim-dap-go/blob/main/lua/dap-go-ts.lua#L13) is written with just a `func_literal` in the `arguments`'s `call_expression`.
It is often the case to use it with a `literal`, see example below: 
```go
package test
import (
"testing"
)
func TestWithSubTests(t *testing.T) {
t.Run("subtest with function literal (is already working)", func(t *testing.T) {})
myFunc := func(t *testing.T) {}
t.Run("subtest with identifier", myFunc)
}
```
Previously, running `:lua require('dap-go').debug_test()` with the cursor on the line with `t.Run("subtest with identifier", myFunc)` was running the parent test `TestWithSubTests` which is running …

fix(sub-tests): supports subtests with an identifier

---

README.md
lua/dap-go.lua

feat: add cwd argument to delve

---

README.md
lua/dap-go.lua

Hi,
Here's a change to automatically set the attached mode for delve so the end-user doesn't have to.
I added it to the config example too but maybe that entire line should be removed with this fix in place, let me know if I should do that.
Br,

fix: automatically set attached mode for delve based on OS

---

lua/dap-go-ts.lua
tests/go.mod
tests/subtest_bar_test.go

see ./tests/subtest_bar_test.go

feat: identifier support for subtests

---

README.md
doc/nvim-dap-go.txt
lua/dap-go.lua

- add `get_build_flags` functions that works the same as `get_arguments` in order to get `go build` flags interactively.
- add additional exposed functions that call `get_build_flags` and `get_arguments` to allow users to be able to reuse these functions within their own customer configurations.
- add local global configuration to store initialized configuration settings.
- updated readme and docs files with relevant change information.

feat: add build flags function for custom configurations

---

README.md
doc/nvim-dap-go.txt
lua/dap-go.lua

I really like the feature of running the closest test to the cursor.
However, I usually make use of the `t.Logf` method which logs stuff when running tests. Without verbosity being turned on these logs will only show when the tests fail.
This PR adds an option to the plugin to enable verbosity. It sets this option to false by default so as to not change the behaviour of the plugin.

feat: Add configuration to enable tests verbosity

---

README.md
doc/nvim-dap-go.txt
lua/dap-go.lua

Currently the Delve port can be defined either randomly or hard-coded by hand.
Hard-coded port allows to know which port to use in remote debug configurations, but in practice with many Go projects, it would be great to set the Delve port in debug configurations.
Luckily `nvim-dap` allows to set an `on_config` callback for an adapter, which can be used to resolve the adapter settings when a debug session starts. This PR implements this `nvim-dap` feature, which can be used with the support of VSCode `launch.json` files to greatly enhance the developer experience.
This potentially resolves https://github.com/leoluz/nvim-dap-go/issues/73

Set the Delve port dynamically for remote debug

---

lua/dap-go-ts.lua

See Neovim breaking change PR: https://github.com/neovim/neovim/pull/30193
Now `iter_matches` by default returns a list of node. 
Iterates over all nodes with backward compatibility using the `all = true` option.
Fixes https://github.com/leoluz/nvim-dap-go/issues/96

fix(closest_test): uses new behavior of the iter_matches function

---

lua/dap-go.lua

nvim-dap had a change to log stdout/stderr of debug adapters to log
files instead of redirecting it to the repl.
(See https://github.com/mfussenegger/nvim-dap/pull/1405)
delve by default outputs print statements on stdout instead of using
output events, which means they're no longer visible.
Setting `outputMode = "remote"` in a configuration causes delve to use
output events, which nvim-dap shows in the repl
See also https://github.com/mfussenegger/nvim-dap/discussions/1407

Add `outputMode` to configurations

---

README.md
doc/nvim-dap-go.txt
lua/dap-go.lua

The issue where delve crashes on windows if started withouth the `detached` option set to `false` was actually solved as part of this issue: https://github.com/go-delve/delve/issues/3864 and it is part of the `1.24.0` release: https://github.com/go-delve/delve/blob/master/CHANGELOG.md#1240-2024-12-18
So I updated the comments to specify that this option needs to be `false` only on versions less than `1.24.0`.

Updated comments for delve Windows detached issue

---

doc/nvim-dap-go.txt
lua/dap-go.lua

Recent changes in nvim-dap behavior required setting `outputMode = "remote"` in debug configs for stdout to be visible in REPL (see https://github.com/leoluz/nvim-dap-go/issues/108 for more info). The problem is now fixed for test scenarios too.
`test_debug` now accepts a `custom_config` argument as a way for users to get around similar problems.
fix #114

fix: debug test does not output to REPL
